import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import { Link, NavLink, Route, Routes, useNavigate, useParams, useSearchParams } from "react-router";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { ArrowLeft, ArrowRight, Check, ChevronDown, CircleAlert, Minus, PackageCheck, Plus, Search, ShoppingBag, SlidersHorizontal, X } from "lucide-react";
import type { Cart, Order, Product } from "@seigyo/contracts";
import { CART_ID, shopApi } from "./api";
import { registerMyShopTools } from "./webmcp";

type Health = { status: "healthy" | "impaired" | "degraded"; updatedAt: number };
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);

function Logo() { return <Link to="/" className="shop-logo"><svg viewBox="0 0 30 30" aria-hidden="true"><path d="M3 24V7l8 7 4-11 4 11 8-7v17H3Z"/><path d="M8 24v-5h14v5"/></svg><span>MyShop</span></Link>; }
function NotFound({ title = "Page not found", detail = "The page you requested is not available." }: { title?: string; detail?: string }) { return <div className="not-found"><h1>{title}</h1><p>{detail}</p><Link to="/">Return home</Link></div>; }

function Shell({ cart, health, openCart, children }: { cart: Cart; health: Health | null; openCart(): void; children: React.ReactNode }) {
  const count = cart.items.reduce((sum, item) => sum + item.quantity, 0);
  return <><div className="notice-bar">Complimentary delivery on orders over $500 <span>Objects for quiet spaces</span></div><header className="shop-header"><Logo/><nav><NavLink to="/collections/all">Collection</NavLink><NavLink to="/collections/Furniture">Furniture</NavLink><NavLink to="/collections/Lighting">Lighting</NavLink><NavLink to="/collections/Ceramics">Ceramics</NavLink><NavLink to="/about">Journal</NavLink></nav><div className="header-actions"><Link to="/search" aria-label="Search"><Search size={18}/></Link><button onClick={openCart} aria-label={`Open bag with ${count} items`}><ShoppingBag size={18}/><span>{count}</span></button></div></header>{health && health.status !== "healthy" && <div className="service-note"><CircleAlert size={14}/><span>{health.status === "degraded" ? "Checkout is currently unavailable. Your bag remains safe." : "Some availability checks are taking longer than usual."}</span></div>}<main>{children}</main><footer><div><Logo/><p>Considered furniture, lighting, and objects made for a slower home.</p></div><div><strong>Explore</strong><Link to="/collections/all">All objects</Link><Link to="/collections/Furniture">Furniture</Link><Link to="/collections/Lighting">Lighting</Link></div><div><strong>Service</strong><Link to="/order">Order lookup</Link><a href="#delivery">Delivery</a><a href="#care">Care guide</a></div><div><strong>Studio notes</strong><p>New releases, maker stories, and material studies.</p><label><input aria-label="Email address" placeholder="Email address"/><ArrowRight size={16}/></label></div></footer><div className="footer-line"><span>© 2026 MyShop</span><span>Douala / Worldwide delivery</span></div></>;
}

function ProductCard({ product }: { product: Product }) { return <article className="product-card"><Link to={`/product/${product.slug}`} className="product-image"><img src={product.image} alt={product.name}/><span className="product-arrow"><ArrowRight size={16}/></span>{product.inventory <= 7 && <i>Low stock</i>}</Link><div className="product-meta"><div><Link to={`/product/${product.slug}`}>{product.name}</Link><span>{product.material}</span></div><strong>{money(product.price)}</strong></div></article>; }

function Home({ products }: { products: Product[] }) { return <><section className="hero"><img src="/images/hero-living-room.png" alt="A calm living room with paper lighting, a dark oak chair, a stone table, and ceramic objects"/><div className="hero-shade"/><div className="hero-copy"><span>Autumn study / 01</span><h1>Objects that hold<br/>the room quietly.</h1><p>A considered collection of tactile forms, honest material, and softened light.</p><Link className="shop-button light" to="/collections/all">View the collection <ArrowRight size={16}/></Link></div><div className="hero-caption"><span>Atelier interior</span><span>Charcoal, oak, stone, paper</span></div></section><section className="intro"><span className="section-count">01 / Collection</span><div><h2>Useful forms.<br/>Lasting presence.</h2><p>We work with independent studios to collect pieces that earn their place through material, proportion, and daily use.</p></div></section><section className="featured-grid">{products.filter(item => item.featured).slice(0, 4).map(item => <ProductCard key={item.id} product={item}/>)}</section><section className="material-story"><div><span className="section-count">Material study / Washed paper</span><h2>Light, held softly.</h2><p>Each folded shade is built by hand, allowing the fiber to shape a warm, quiet glow.</p><Link to="/collections/Lighting">Explore lighting <ArrowRight size={15}/></Link></div><img src="/images/paper-pendant.png" alt="Handmade folded paper pendant light"/></section><section className="editorial-row"><img src="/images/oak-chair.png" alt="Blackened oak lounge chair with cane seat"/><div><span className="section-count">Made for pause</span><h2>The chair as a place, not an object.</h2><p>Low profiles, generous angles, and natural cane create a seat that becomes more familiar with time.</p><Link className="shop-button dark" to="/collections/Furniture">Shop furniture <ArrowRight size={16}/></Link></div></section></>;
}

function Collection({ products }: { products: Product[] }) { const { category = "all" } = useParams(); const [sort, setSort] = useState("featured"); const visible = useMemo(() => { const base = category === "all" ? products : products.filter(item => item.category.toLowerCase() === category.toLowerCase()); return [...base].sort((a,b) => sort === "low" ? a.price-b.price : sort === "high" ? b.price-a.price : Number(b.featured)-Number(a.featured)); }, [products, category, sort]); return <div className="collection-page"><header className="collection-head"><span className="section-count">Collection / {category}</span><h1>{category === "all" ? "All objects" : category}</h1><p>{visible.length} considered pieces for the modern home.</p></header><div className="collection-tools"><span>{visible.length} pieces</span><label><SlidersHorizontal size={14}/><select value={sort} onChange={event => setSort(event.target.value)} aria-label="Sort products"><option value="featured">Featured</option><option value="low">Price, low to high</option><option value="high">Price, high to low</option></select><ChevronDown size={13}/></label></div><div className="collection-grid">{visible.map(product => <ProductCard product={product} key={product.id}/>)}</div></div>; }

function ProductPage({ products, add }: { products: Product[]; add(productId: string, quantity?: number): Promise<void> }) { const { slug = "" } = useParams(); const product = products.find(item => item.slug === slug); const [qty, setQty] = useState(1); const [added, setAdded] = useState(false); if (!product) return <NotFound title="Object not found" detail="This object is no longer in the collection."/>; const submit = async () => { await add(product.id, qty); setAdded(true); window.setTimeout(() => setAdded(false), 1800); }; return <div className="product-page"><div className="product-gallery"><button aria-label="Only product image" disabled><ArrowLeft size={16}/></button><img src={product.image} alt={product.name}/><span>01 / 01</span></div><div className="product-info"><Link to={`/collections/${product.category}`}>{product.category}</Link><h1>{product.name}</h1><p className="material">{product.material}</p><strong className="product-price">{money(product.price)}</strong><p className="description">{product.description}</p><dl><div><dt>Dimensions</dt><dd>{product.dimensions}</dd></div><div><dt>Availability</dt><dd>{product.inventory > 8 ? "In stock" : `Only ${product.inventory} remaining`}</dd></div><div><dt>Delivery</dt><dd>2 to 4 weeks</dd></div></dl><div className="add-row"><div className="quantity"><button onClick={() => setQty(value => Math.max(1,value-1))} aria-label="Decrease quantity"><Minus size={14}/></button><span>{qty}</span><button onClick={() => setQty(value => Math.min(10,value+1))} aria-label="Increase quantity"><Plus size={14}/></button></div><button className="add-button" onClick={submit}>{added ? <><Check size={16}/>Added to bag</> : <>Add to bag <ArrowRight size={16}/></>}</button></div><div className="product-notes"><details open><summary>Material and care <Plus size={14}/></summary><p>Wipe with a soft dry cloth. Keep away from prolonged direct moisture and strong heat.</p></details><details><summary>Shipping and returns <Plus size={14}/></summary><p>White-glove delivery is available. Returns are accepted within 14 days.</p></details></div></div></div>; }

function SearchPage({ products }: { products: Product[] }) { const [params, setParams] = useSearchParams(); const query = params.get("q") ?? ""; const results = products.filter(item => `${item.name} ${item.material} ${item.category}`.toLowerCase().includes(query.toLowerCase())); return <div className="search-page"><span className="section-count">Search the collection</span><form onSubmit={event => event.preventDefault()}><Search size={24}/><input autoFocus value={query} onChange={event => setParams(event.target.value ? { q:event.target.value } : {})} placeholder="Type to search" aria-label="Search products"/><span>{query ? `${results.length} results` : ""}</span></form>{query ? <div className="collection-grid">{results.map(item => <ProductCard product={item} key={item.id}/>)}</div> : <div className="search-suggestions"><p>Popular searches</p>{["Paper lighting","Oak seating","Ceramic vessels","Textiles"].map(item => <button key={item} onClick={() => setParams({ q:item })}>{item}<ArrowRight size={14}/></button>)}</div>}</div>; }

function Checkout({ cart, products, refresh }: { cart: Cart; products: Product[]; refresh(): Promise<void> }) { const navigate = useNavigate(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const total = cart.items.reduce((sum,item) => sum + item.quantity * (products.find(p => p.id === item.productId)?.price ?? 0),0); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); try { const order = await shopApi.checkout<Order>({ cartId:CART_ID, name:String(form.get("name")), email:String(form.get("email")), address:String(form.get("address")), requestId:"checkout-web-005", idempotencyKey:crypto.randomUUID() }); await refresh(); navigate(`/confirmation/${order.id}`); } catch (caught) { setError(caught instanceof Error ? caught.message : "Checkout could not be completed."); } finally { setBusy(false); } }; if (!cart.items.length) return <div className="not-found"><ShoppingBag size={30}/><h1>Your bag is empty</h1><Link to="/collections/all">Explore the collection</Link></div>; return <div className="checkout-page"><div className="checkout-form"><Link to="/cart"><ArrowLeft size={14}/> Return to bag</Link><span className="section-count">Secure checkout</span><h1>Delivery details</h1>{error && <div className="checkout-error" role="alert"><CircleAlert size={18}/><div><strong>We could not complete your order</strong><p>{error}</p><small>Your bag is safe. Please review the details and try again.</small></div></div>}<form onSubmit={submit}><label><span>Full name</span><input name="name" required minLength={2} defaultValue="Randy B."/></label><label><span>Email</span><input name="email" type="email" required defaultValue="randy@example.com"/></label><label><span>Delivery address</span><textarea name="address" required minLength={8} defaultValue="18 Studio Lane, Douala, Cameroon"/></label><button className="place-order" disabled={busy}>{busy ? "Processing securely..." : <>Place order <span>{money(total)}</span></>}</button></form></div><OrderSummary cart={cart} products={products}/></div>; }

function OrderSummary({ cart, products }: { cart: Cart; products: Product[] }) { const rows = cart.items.map(item => ({ ...item, product:products.find(p => p.id === item.productId)! })).filter(item => item.product); const subtotal = rows.reduce((sum,item) => sum+item.quantity*item.product.price,0); return <aside className="order-summary"><span className="section-count">Your order</span>{rows.map(item => <div className="summary-item" key={item.productId}><img src={item.product.image} alt=""/><div><strong>{item.product.name}</strong><span>Quantity {item.quantity}</span></div><b>{money(item.product.price*item.quantity)}</b></div>)}<dl><div><dt>Subtotal</dt><dd>{money(subtotal)}</dd></div><div><dt>Delivery</dt><dd>{subtotal >= 500 ? "Complimentary" : "$45"}</dd></div><div className="total"><dt>Total</dt><dd>{money(subtotal + (subtotal >= 500 ? 0 : 45))}</dd></div></dl></aside>; }

function CartPage({ cart, products, update }: { cart: Cart; products: Product[]; update(productId:string,quantity:number):Promise<void> }) { const rows=cart.items.map(item=>({...item,product:products.find(p=>p.id===item.productId)!})).filter(item=>item.product); return <div className="cart-page"><span className="section-count">Your selection</span><h1>Shopping bag</h1>{rows.length===0?<div className="empty-cart"><ShoppingBag size={25}/><p>Your bag is ready for something considered.</p><Link to="/collections/all">Explore all objects</Link></div>:<><div className="cart-list">{rows.map(item=><div className="cart-line" key={item.productId}><img src={item.product.image} alt={item.product.name}/><div><Link to={`/product/${item.product.slug}`}>{item.product.name}</Link><span>{item.product.material}</span><button onClick={()=>update(item.productId,0)}>Remove</button></div><div className="quantity"><button aria-label={`Decrease ${item.product.name} quantity`} onClick={()=>update(item.productId,Math.max(0,item.quantity-1))}><Minus size={13}/></button><span>{item.quantity}</span><button aria-label={`Increase ${item.product.name} quantity`} disabled={item.quantity >= 10} onClick={()=>update(item.productId,Math.min(10,item.quantity+1))}><Plus size={13}/></button></div><strong>{money(item.product.price*item.quantity)}</strong></div>)}</div><div className="cart-total"><div><span>Subtotal</span><strong>{money(rows.reduce((s,i)=>s+i.product.price*i.quantity,0))}</strong></div><p>Delivery calculated at checkout.</p><Link className="place-order" to="/checkout">Continue to checkout <ArrowRight size={16}/></Link></div></>}</div>; }

function Confirmation({ products }: { products: Product[] }) { const { id="" }=useParams(); const [order,setOrder]=useState<Order|null>(null); const [missing,setMissing]=useState(false); useEffect(()=>{setMissing(false);void shopApi.order<Order>(id).then(setOrder).catch(()=>setMissing(true))},[id]); if(missing)return <NotFound title="Order not found" detail="Check the order number and try again."/>; if(!order)return <div className="not-found" role="status"><div className="page-loader"/><p>Retrieving your order</p></div>; return <div className="confirmation"><span className="confirm-icon"><PackageCheck size={30}/></span><span className="section-count">Order confirmed / {order.id}</span><h1>Thank you, {order.name.split(" ")[0]}.</h1><p>Your order is confirmed. We sent the details to {order.email}.</p><div className="confirm-meta"><div><span>Delivery to</span><strong>{order.address}</strong></div><div><span>Total</span><strong>{money(order.total)}</strong></div><div><span>Status</span><strong>{order.status}</strong></div></div><div className="confirm-products">{order.items.map(item=>{const product=products.find(p=>p.id===item.productId);return product?<div key={item.productId}><img src={product.image} alt={product.name}/><span>{product.name} × {item.quantity}</span></div>:null})}</div><Link className="shop-button light" to="/collections/all">Continue exploring <ArrowRight size={15}/></Link></div>; }

function OrderLookup() { const navigate=useNavigate(); const [id,setId]=useState(""); return <div className="order-lookup"><span className="section-count">Customer service</span><h1>Find your order</h1><p>Enter the order number from your confirmation.</p><form onSubmit={event=>{event.preventDefault();if(id)navigate(`/confirmation/${id}`)}}><input aria-label="Order number" value={id} onChange={event=>setId(event.target.value)} placeholder="ORD-1001"/><button>Look up order <ArrowRight size={15}/></button></form></div>; }

function CartDrawer({ open, close, cart, products, update }: { open:boolean;close():void;cart:Cart;products:Product[];update(productId:string,quantity:number):Promise<void> }) { const reduceMotion=useReducedMotion(); const rows=cart.items.map(item=>({...item,product:products.find(p=>p.id===item.productId)!})).filter(item=>item.product); const total=rows.reduce((sum,item)=>sum+item.product.price*item.quantity,0); return <AnimatePresence>{open&&<motion.div className="drawer-backdrop" initial={reduceMotion?false:{opacity:0}} animate={{opacity:1}} exit={reduceMotion?undefined:{opacity:0}} onMouseDown={close}><motion.aside className="cart-drawer" initial={reduceMotion?false:{x:"100%"}} animate={{x:0}} exit={reduceMotion?undefined:{x:"100%"}} transition={{duration:reduceMotion?0:.22,ease:[.2,.7,.2,1]}} onMouseDown={event=>event.stopPropagation()}><header><span>Shopping bag / {cart.items.length}</span><button onClick={close} aria-label="Close shopping bag"><X size={18}/></button></header><div className="drawer-items">{rows.length===0?<div className="empty-cart"><ShoppingBag size={24}/><p>Your bag is empty.</p></div>:rows.map(item=><div className="drawer-item" key={item.productId}><img src={item.product.image} alt={item.product.name}/><div><strong>{item.product.name}</strong><span>{item.product.material}</span><div className="quantity"><button aria-label={`Decrease ${item.product.name} quantity`} onClick={()=>update(item.productId,Math.max(0,item.quantity-1))}><Minus size={12}/></button><span>{item.quantity}</span><button aria-label={`Increase ${item.product.name} quantity`} disabled={item.quantity>=10} onClick={()=>update(item.productId,Math.min(10,item.quantity+1))}><Plus size={12}/></button></div></div><b>{money(item.product.price*item.quantity)}</b></div>)}</div>{rows.length>0&&<div className="drawer-foot"><div><span>Subtotal</span><strong>{money(total)}</strong></div><Link to="/checkout" onClick={close}>Checkout <ArrowRight size={15}/></Link><Link to="/cart" onClick={close}>View bag</Link></div>}</motion.aside></motion.div>}</AnimatePresence>; }

export function App() {
  const [products,setProducts]=useState<Product[]>([]); const [cart,setCart]=useState<Cart>({id:CART_ID,items:[],updatedAt:0}); const [health,setHealth]=useState<Health|null>(null); const [drawer,setDrawer]=useState(false); const [appError,setAppError]=useState("");
  useEffect(() => { if (!drawer) return; const invoker = document.activeElement as HTMLElement | null; const dialog = document.querySelector<HTMLElement>(".cart-drawer"); if (!dialog) return; dialog.setAttribute("role", "dialog"); dialog.setAttribute("aria-modal", "true"); dialog.setAttribute("aria-label", "Shopping bag"); const focusable = () => [...dialog.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),input:not([disabled]),[tabindex]:not([tabindex="-1"])')]; focusable()[0]?.focus(); const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") { setDrawer(false); return; } if (event.key !== "Tab") return; const items = focusable(); const first = items[0]; const last = items.at(-1); if (!first || !last) return; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener("keydown", onKey); return () => { document.removeEventListener("keydown", onKey); invoker?.focus(); }; }, [drawer]);
  const refresh=async()=>{try{const [nextProducts,nextCart,nextHealth]=await Promise.all([shopApi.products<Product[]>(),shopApi.cart<Cart>(CART_ID),shopApi.health<Health>()]);setProducts(nextProducts);setCart(nextCart);setHealth(nextHealth);setAppError("")}catch(error){setAppError(error instanceof Error?error.message:"MyShop could not load.")}};
  useEffect(()=>{void refresh();return registerMyShopTools()},[]);
  const update=async(productId:string,quantity:number)=>{try{setCart(await shopApi.updateCart<Cart>(CART_ID,productId,quantity));setAppError("")}catch(error){setAppError(error instanceof Error?error.message:"The bag could not be updated.")}};
  const add=async(productId:string,quantity=1)=>{const current=cart.items.find(item=>item.productId===productId)?.quantity??0;await update(productId,current+quantity);setDrawer(true)};
  return <><Shell cart={cart} health={health} openCart={()=>setDrawer(true)}>{appError&&<div className="checkout-error app-error" role="alert"><CircleAlert size={18}/><div><strong>MyShop could not connect</strong><p>{appError}</p><button onClick={()=>void refresh()}>Try again</button></div></div>}<Routes><Route path="/" element={<Home products={products}/>}/><Route path="/collections/:category" element={<Collection products={products}/>}/><Route path="/product/:slug" element={<ProductPage products={products} add={add}/>}/><Route path="/search" element={<SearchPage products={products}/>}/><Route path="/cart" element={<CartPage cart={cart} products={products} update={update}/>}/><Route path="/checkout" element={<Checkout cart={cart} products={products} refresh={refresh}/>}/><Route path="/confirmation/:id" element={<Confirmation products={products}/>}/><Route path="/order" element={<OrderLookup/>}/><Route path="/about" element={<div className="journal"><span className="section-count">Journal / 06</span><h1>Notes on quiet utility.</h1><img src="/images/umber-vessel.png" alt="Umber ceramic vessel"/><p>We collect objects that become more interesting through use. Their surfaces record a life rather than resist it.</p></div>}/><Route path="*" element={<NotFound/>}/></Routes></Shell><CartDrawer open={drawer} close={()=>setDrawer(false)} cart={cart} products={products} update={update}/></>;
}
